spring.application.name=local-service-finder
spring.datasource.url=jdbc:mysql://localhost:3306/local_service
spring.datasource.username=root
spring.datasource.password=Jeeva

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080